### ISSUE TITLE
Rotation of Configuration Dialog Icon

### ISSUE THREAD

**Issue by VirgiliaBeatrice** [JitsiPartyTeam/jitsi-party#28]
**Describe the bug**
When you rotate your icon, the icon of the configuration icon is also rotated.

**Expected behavior**
The orientation of the configuration icon should be kept as constant.

**Screenshots**
![BugOnRotation](https://user-images.githubusercontent.com/9668444/85968069-fadf6e80-b9fe-11ea-8c3c-b769ce9f98b4.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome

**Comment by hasevr** [comment]
It seems solved.
