### ISSUE TITLE
Audio can't switch back to stereo mode

### ISSUE THREAD

**Issue by zlguo1996** [JitsiPartyTeam/jitsi-party#53]
After click the button in the left bottom, it success to swtich to mono audio mode.
But if clicked again, it does not back into stereo mode.
![image](https://user-images.githubusercontent.com/17405914/88637605-57fd3b80-d0f5-11ea-8ff0-d8fb172fd281.png)

**Comment by hasevr** [comment]
This was my mistake and fixed and already pushed to master.
old:          this.audioElement.muted
new:          this.audioElement.pause()
