### ISSUE TITLE
Speaker indicator

### ISSUE THREAD

**Issue by zlguo1996** [JitsiPartyTeam/jitsi-party#9]
## Motivation
Currently, the only way of knowing who is speaking is  judge from video and audio content. But that is not easy enough for users to identify who are speaking to them. Thus, other hints would be needed.

**Comment by zlguo1996** [comment]
- A simple solution is use light around avatar. The light would blink when user is speaking.
- Since all participants have orientation. This information could also be used for indicating who is speaking to who. That information should also be reflected in speaker indicator.

**Comment by VirgiliaBeatrice** [comment]
The state of a speaking indicator in a conference room could be obtained from lib-jitsi-meet.
We need to add a state in the store.

**Comment by hasevr** [comment]
I've add audio meter which shows sound level of each participants.
